/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/car.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/car.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials['Lamborghini-text-logo-1440x900.002']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.047']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.048']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Material.049']} />
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Material.055']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.040']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['Material.057']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.044']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/car.glb')
